# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-03 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('campus', models.CharField(blank=True, choices=[(b'van', b'Vancouver'), (b'oka', b'Okanagan')], max_length=255, null=True)),
                ('raw_name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('campus', models.CharField(blank=True, choices=[(b'van', b'Vancouver'), (b'oka', b'Okanagan')], max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[(b'm', b'Male'), (b'f', b'Female')], max_length=1, null=True)),
                ('remuneration', models.IntegerField()),
                ('expenses', models.IntegerField()),
                ('slug', models.CharField(max_length=255)),
                ('rating', models.IntegerField(default=0)),
                ('num_ratings', models.IntegerField(default=0)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salarydb.Department')),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=255)),
                ('campus', models.CharField(blank=True, choices=[(b'van', b'Vancouver'), (b'oka', b'Okanagan')], max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'faculties',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=500)),
                ('employee', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salarydb.Faculty'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salarydb.Position'),
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salarydb.Faculty'),
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salarydb.Department'),
        ),
    ]
