# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-03 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salarydb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('remuneration', models.IntegerField()),
                ('expenses', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='expenses',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='remuneration',
        ),
        migrations.AddField(
            model_name='salary',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salarydb.Employee'),
        ),
    ]
